captainVersion: 4
services:
    $$cap_appname:
        image: ethibox/collabora-online:$$cap_collabora_version
        volumes:
            - $$cap_appname-data:/var/lib/libreoffice
        restart: always
        environment:
            domain: $$cap_domain
            username: $$cap_username
            password: $$cap_password
        caproverExtra:
            containerHttpPort: 9980
caproverOneClickApp:
    variables:
        - id: $$cap_collabora_version
          label: Collabora Version
          defaultValue: '23.05'
          description: Collabora Online version
          validRegex: /.{1,}/
        - id: $$cap_domain
          label: Domain
          description: Domain for Collabora (e.g., nextcloud.domain.com)
        - id: $$cap_username
          label: Admin Username
          defaultValue: admin
        - id: $$cap_password
          label: Admin Password
          description: Password for admin user
    instructions:
        start: Deploying Collabora Online for document editing.
        end: Collabora has been deployed! Visit http://$$cap_appname.$$cap_root_domain for document editing interface.
    displayName: Collabora Online
    isOfficial: false
    description: LibreOffice-based online office. Edit documents, spreadsheets, and presentations directly in your browser.
