captainVersion: 4
services:
    $$cap_appname:
        image: directus/directus:$$cap_directus_version
        volumes:
            - $$cap_appname-uploads:/directus/uploads
            - $$cap_appname-extensions:/directus/extensions
        restart: always
        environment:
            KEY: $$cap_key
            SECRET: $$cap_secret
            ADMIN_EMAIL: $$cap_admin_email
            ADMIN_PASSWORD: $$cap_admin_password
            DB_CLIENT: sqlite3
            DB_FILENAME: /directus/database/data.db
        caproverExtra:
            containerHttpPort: 8055
caproverOneClickApp:
    variables:
        - id: $$cap_directus_version
          label: Directus Version
          defaultValue: '10.8'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/directus/directus/tags
          validRegex: /.{1,}/
        - id: $$cap_key
          label: Key
          description: Random key for security (generate a random string).
        - id: $$cap_secret
          label: Secret
          description: Random secret for security (generate a random string).
        - id: $$cap_admin_email
          label: Admin Email
          description: Email address for the admin user.
        - id: $$cap_admin_password
          label: Admin Password
          description: Password for the admin user.
    instructions:
        start: Deploying Directus data platform and headless CMS.
        end: Directus has been deployed! Visit http://$$cap_appname.$$cap_root_domain to login with your admin credentials.
    displayName: Directus
    isOfficial: false
    description: Data platform and headless CMS. Wraps any SQL database with a real-time GraphQL+REST API and an intuitive admin app.
