captainVersion: 4
services:
    $$cap_appname:
        image: duplicati/duplicati:$$cap_duplicati_version
        volumes:
            - $$cap_appname-data:/data
            - $$cap_appname-config:/config
        restart: always
        environment:
            PUID: 1000
            PGID: 1000
            TZ: $$cap_timezone
        caproverExtra:
            containerHttpPort: 8200
caproverOneClickApp:
    variables:
        - id: $$cap_duplicati_version
          label: Duplicati Version
          defaultValue: v2.0.7.1-2.0.7.1_beta_2023-05-25
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/duplicati/duplicati/tags
          validRegex: /.{1,}/
        - id: $$cap_timezone
          label: Timezone
          defaultValue: 'UTC'
          description: Timezone (e.g., America/New_York, Europe/London)
    instructions:
        start: Deploying Duplicati backup solution.
        end: Duplicati has been deployed! Access the web interface at http://$$cap_appname.$$cap_root_domain and configure your backup targets.
    displayName: Duplicati
    isOfficial: false
    description: Encrypted backup solution. Store securely encrypted backups online with support for incremental backups and various cloud providers.
