captainVersion: 4
services:
    $$cap_appname:
        image: gitlab/gitlab-ce:$$cap_gitlab_version
        volumes:
            - $$cap_appname-config:/etc/gitlab
            - $$cap_appname-logs:/var/log/gitlab
            - $$cap_appname-data:/var/opt/gitlab
        restart: always
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://$$cap_appname.$$cap_root_domain'
                gitlab_rails['gitlab_shell_ssh_port'] = 2224
        caproverExtra:
            containerHttpPort: 80
caproverOneClickApp:
    variables:
        - id: $$cap_gitlab_version
          label: GitLab Version
          defaultValue: '16.7.0-ce.0'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/gitlab/gitlab-ce/tags
          validRegex: /.{1,}/
    instructions:
        start: Deploying GitLab Community Edition. This may take several minutes to initialize.
        end: GitLab has been deployed! Visit http://$$cap_appname.$$cap_root_domain and login with username 'root'. The initial root password can be found in the logs.
    displayName: GitLab CE
    isOfficial: false
    description: Self-hosted Git repository management, code reviews, issue tracking, and CI/CD. Complete DevOps platform delivered as a single application.
