captainVersion: 4
services:
    $$cap_appname:
        image: registry.gitlab.com/gitlab-org/build/cng/gitlab-runner:$$cap_runner_version
        volumes:
            - $$cap_appname-config:/etc/gitlab-runner
        restart: always
        environment:
            GITLAB_URL: $$cap_gitlab_url
caproverOneClickApp:
    variables:
        - id: $$cap_runner_version
          label: GitLab Runner Version
          defaultValue: '16.7.0'
          description: GitLab Runner version tag
          validRegex: /.{1,}/
        - id: $$cap_gitlab_url
          label: GitLab URL
          defaultValue: 'https://gitlab.com'
          description: URL of your GitLab instance
    instructions:
        start: Deploying GitLab Runner for CI/CD jobs execution.
        end: GitLab Runner has been deployed! Register it with your GitLab instance using the registration token.
    displayName: GitLab Runner
    isOfficial: false
    description: GitLab CI/CD runner. Execute jobs and pipelines for GitLab CI/CD. Can be registered with gitlab.com or self-hosted.
