captainVersion: 4
services:
    $$cap_appname:
        image: grafana/grafana:$$cap_grafana_version
        volumes:
            - $$cap_appname-data:/var/lib/grafana
        restart: always
        environment:
            GF_SECURITY_ADMIN_USER: $$cap_admin_user
            GF_SECURITY_ADMIN_PASSWORD: $$cap_admin_password
            GF_INSTALL_PLUGINS: $$cap_plugins
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_grafana_version
          label: Grafana Version
          defaultValue: '10.2.3'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/grafana/grafana/tags
          validRegex: /.{1,}/
        - id: $$cap_admin_user
          label: Admin Username
          defaultValue: admin
        - id: $$cap_admin_password
          label: Admin Password
          description: Password for the admin user.
        - id: $$cap_plugins
          label: Plugins
          defaultValue: ''
          description: 'Comma-separated list of plugins to install (optional). Example: grafana-clock-panel,grafana-simple-json-datasource'
    instructions:
        start: Deploying Grafana analytics and monitoring platform.
        end: Grafana has been deployed! Visit http://$$cap_appname.$$cap_root_domain to login with your credentials.
    displayName: Grafana
    isOfficial: false
    description: Analytics and monitoring platform. Query, visualize, alert on, and understand your metrics with beautiful dashboards.
