captainVersion: 4
services:
    $$cap_appname:
        image: jellyfin/jellyfin:$$cap_jellyfin_version
        volumes:
            - $$cap_appname-config:/config
            - $$cap_appname-cache:/cache
        restart: always
        caproverExtra:
            containerHttpPort: 8096
caproverOneClickApp:
    variables:
        - id: $$cap_jellyfin_version
          label: Jellyfin Version
          defaultValue: '10.8.13'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/jellyfin/jellyfin/tags
          validRegex: /.{1,}/
    instructions:
        start: Deploying Jellyfin media server.
        end: Jellyfin has been deployed! Access it at http://$$cap_appname.$$cap_root_domain and complete the setup wizard. Add your media folders after setup.
    displayName: Jellyfin
    isOfficial: false
    description: Free media server for organizing, managing, and streaming your media. Open-source alternative to Plex and Emby.
