captainVersion: 4
services:
    $$cap_appname:
        image: jenkins/jenkins:$$cap_jenkins_version
        volumes:
            - $$cap_appname-data:/var/jenkins_home
        restart: always
        environment:
            JENKINS_OPTS: '--prefix=/jenkins'
        caproverExtra:
            containerHttpPort: 8080
caproverOneClickApp:
    variables:
        - id: $$cap_jenkins_version
          label: Jenkins Version
          defaultValue: lts-jdk17
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/jenkins/jenkins/tags
          validRegex: /.{1,}/
    instructions:
        start: Deploying Jenkins automation server for CI/CD.
        end: Jenkins has been deployed! Visit http://$$cap_appname.$$cap_root_domain to complete setup. Get initial admin password from logs.
    displayName: Jenkins
    isOfficial: false
    description: The leading open source automation server. Jenkins provides hundreds of plugins to support building, deploying and automating any project.
