---
captainVersion: 4
services:
    $$cap_appname:
        build: .
        restart: always
        ports:
            - $$cap_rdp_port:3389
        environment:
            RDP_PORT: $$cap_rdp_port
            WEBUI_PORT: 5000
        caproverExtra:
            containerHttpPort: 5000
            dockerfileLines:
                - FROM kalilinux/kali-rolling
                - RUN apt-get update && apt-get install -y xrdp python3 python3-pip curl
                - RUN apt-get update && apt-get install -y kali-linux-large
                - RUN pip3 install --no-cache-dir flask psutil
                - RUN echo "xfce4-session" > /etc/skel/.xsession
                - RUN mkdir -p /opt/kali-webui
                - RUN curl -fsSL https://raw.githubusercontent.com/caprover/one-click-apps/master/public/assets/kali-linux-gui/app.py -o /opt/kali-webui/app.py
                - RUN curl -fsSL https://raw.githubusercontent.com/caprover/one-click-apps/master/public/assets/kali-linux-gui/start.sh -o /opt/kali-webui/start.sh
                - RUN chmod +x /opt/kali-webui/start.sh
                - EXPOSE 3389
                - EXPOSE 5000
                - CMD ["/opt/kali-webui/start.sh"]
caproverOneClickApp:
    variables:
        - id: $$cap_rdp_port
          label: RDP Port
          defaultValue: 3389
    instructions:
        start:
            This will deploy a Kali Linux container with GUI and remote desktop
            support. A lightweight Flask web UI is also included to display
            server statistics.
        end: Kali Linux is deployed and accessible via RDP. Use a Remote Desktop
            client to connect using the IP address/domain name and the RDP port
            specified during deployment. The server stats web UI is available
            on the CapRover-assigned URL.
    displayName: Kali Linux with GUI
    isOfficial: false
    description: Kali Linux container with GUI and remote desktop support.
