captainVersion: 4
services:
    $$cap_appname:
        image: listmonk/listmonk:$$cap_listmonk_version
        volumes:
            - $$cap_appname-data:/listmonk
        restart: always
        environment:
            TZ: $$cap_timezone
        caproverExtra:
            containerHttpPort: 9000
caproverOneClickApp:
    variables:
        - id: $$cap_listmonk_version
          label: Listmonk Version
          defaultValue: v3.0.0
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/listmonk/listmonk/tags
          validRegex: /.{1,}/
        - id: $$cap_timezone
          label: Timezone
          defaultValue: America/New_York
    instructions:
        start: Deploying Listmonk newsletter and mailing list manager.
        end: Listmonk has been deployed! Visit http://$$cap_appname.$$cap_root_domain to set up your mailing lists.
    displayName: Listmonk
    isOfficial: false
    description: Newsletter and mailing list manager. Self-hosted, high-performance platform for managing subscribers and campaigns.
