captainVersion: 4
services:
    $$cap_appname:
        image: mariadb:$$cap_mariadb_version
        volumes:
            - $$cap_appname-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_root_password
            MYSQL_DATABASE: $$cap_db_name
            MYSQL_USER: $$cap_db_user
            MYSQL_PASSWORD: $$cap_db_password
        caproverExtra:
            notExposeAsWebApp: true
caproverOneClickApp:
    variables:
        - id: $$cap_mariadb_version
          label: MariaDB Version
          defaultValue: '11.2'
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/mariadb/tags
          validRegex: /.{1,}/
        - id: $$cap_root_password
          label: Root Password
          description: MariaDB root password.
        - id: $$cap_db_name
          label: Database Name
          defaultValue: mydb
          description: Initial database name.
        - id: $$cap_db_user
          label: Database User
          defaultValue: user
          description: Database username.
        - id: $$cap_db_password
          label: Database Password
          description: Database password.
    instructions:
        start: Deploying MariaDB relational database.
        end: MariaDB has been deployed! Connect using the provided credentials on port 3306.
    displayName: MariaDB
    isOfficial: false
    description: MySQL-compatible relational database. Community-developed fork of MySQL with enhanced features and performance.
