captainVersion: 4
services:
    $$cap_appname:
        image: miniflux/miniflux:$$cap_miniflux_version
        depends_on:
            - $$cap_appname-db
        restart: always
        environment:
            DATABASE_URL: postgres://miniflux:$$cap_db_password@$$cap_appname-db/miniflux?sslmode=disable
            RUN_MIGRATIONS: '1'
            CREATE_ADMIN: '1'
            ADMIN_USERNAME: $$cap_admin_username
            ADMIN_PASSWORD: $$cap_admin_password
        caproverExtra:
            containerHttpPort: 8080
    $$cap_appname-db:
        image: postgres:15
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: miniflux
            POSTGRES_USER: miniflux
            POSTGRES_PASSWORD: $$cap_db_password
        caproverExtra:
            notExposeAsWebApp: true
caproverOneClickApp:
    variables:
        - id: $$cap_miniflux_version
          label: Miniflux Version
          defaultValue: '2.1.0'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/miniflux/miniflux/tags
          validRegex: /.{1,}/
        - id: $$cap_admin_username
          label: Admin Username
          defaultValue: admin
          description: Admin username
        - id: $$cap_admin_password
          label: Admin Password
          description: Admin password
        - id: $$cap_db_password
          label: Database Password
          description: PostgreSQL password
    instructions:
        start: Deploying Miniflux RSS reader.
        end: Miniflux has been deployed! Access it at http://$$cap_appname.$$cap_root_domain with your admin credentials.
    displayName: Miniflux
    isOfficial: false
    description: Minimalist and opinionated RSS feed reader. Fast, simple, and focused on reading with keyboard shortcuts and integrations.
