captainVersion: 4
services:
    $$cap_appname:
        image: mongo:$$cap_mongodb_version
        volumes:
            - $$cap_appname-data:/data/db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: $$cap_root_user
            MONGO_INITDB_ROOT_PASSWORD: $$cap_root_password
        caproverExtra:
            notExposeAsWebApp: true
caproverOneClickApp:
    variables:
        - id: $$cap_mongodb_version
          label: MongoDB Version
          defaultValue: '7.0'
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/mongo/tags
          validRegex: /.{1,}/
        - id: $$cap_root_user
          label: Root Username
          defaultValue: admin
          description: MongoDB root username.
        - id: $$cap_root_password
          label: Root Password
          description: MongoDB root password.
    instructions:
        start: Deploying MongoDB NoSQL database.
        end: MongoDB has been deployed! Connect using the provided credentials on port 27017.
    displayName: MongoDB
    isOfficial: false
    description: NoSQL document database. MongoDB stores data in flexible, JSON-like documents with dynamic schemas.
