captainVersion: 4
services:
    $$cap_appname:
        image: openspeedtest/latest:$$cap_ost_version
        restart: always
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_ost_version
          label: OpenSpeedTest Version
          defaultValue: v2.0.5
          description: OpenSpeedTest version
          validRegex: /.{1,}/
    instructions:
        start: Deploying OpenSpeedTest speed test server.
        end: OpenSpeedTest has been deployed! Visit http://$$cap_appname.$$cap_root_domain to test your internet speed.
    displayName: OpenSpeedTest
    isOfficial: false
    description: Self-hosted speed test. Test your internet connection speed with HTML5 without Flash or Java.
