captainVersion: 4
services:
    $$cap_appname-redis:
        image: redis:$$cap_redis_version
        restart: always
    $$cap_appname-postgres:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: outline
            POSTGRES_USER: outline
            POSTGRES_PASSWORD: $$cap_db_password
    $$cap_appname:
        image: outlinewiki/outline:$$cap_outline_version
        restart: always
        environment:
            SECRET_KEY: $$cap_secret_key
            UTILS_SECRET: $$cap_utils_secret
            DATABASE_URL: postgres://outline:$$cap_db_password@$$cap_appname-postgres:5432/outline
            REDIS_URL: redis://$$cap_appname-redis:6379
            URL: http://$$cap_appname.$$cap_root_domain
            PORT: '3000'
        depends_on:
            - $$cap_appname-postgres
            - $$cap_appname-redis
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_outline_version
          label: Outline Version
          defaultValue: '0.74'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/outlinewiki/outline/tags
          validRegex: /.{1,}/
        - id: $$cap_postgres_version
          label: PostgreSQL Version
          defaultValue: '15'
        - id: $$cap_redis_version
          label: Redis Version
          defaultValue: '7'
        - id: $$cap_db_password
          label: Database Password
        - id: $$cap_secret_key
          label: Secret Key
          description: Generate a random 32-character secret key.
        - id: $$cap_utils_secret
          label: Utils Secret
          description: Generate another random 32-character secret.
    instructions:
        start: Deploying Outline knowledge base and wiki.
        end: Outline has been deployed! Visit http://$$cap_appname.$$cap_root_domain to set up authentication. Note - You need to configure OAuth provider.
    displayName: Outline
    isOfficial: false
    description: Knowledge base and wiki for teams. Fast, collaborative, and beautiful wiki with real-time editing and Markdown support.
