captainVersion: 4
services:
    $$cap_appname:
        image: photoprism/photoprism:$$cap_photoprism_version
        volumes:
            - $$cap_appname-storage:/photoprism/storage
            - $$cap_appname-originals:/photoprism/originals
        restart: always
        environment:
            PHOTOPRISM_ADMIN_PASSWORD: $$cap_admin_password
            PHOTOPRISM_SITE_URL: http://$$cap_appname.$$cap_root_domain
            PHOTOPRISM_DISABLE_TLS: 'true'
            PHOTOPRISM_DATABASE_DRIVER: sqlite
        caproverExtra:
            containerHttpPort: 2342
caproverOneClickApp:
    variables:
        - id: $$cap_photoprism_version
          label: PhotoPrism Version
          defaultValue: '231128'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/photoprism/photoprism/tags
          validRegex: /.{1,}/
        - id: $$cap_admin_password
          label: Admin Password
          description: Admin password for PhotoPrism
    instructions:
        start: Deploying PhotoPrism photo management application.
        end: PhotoPrism has been deployed! Access it at http://$$cap_appname.$$cap_root_domain with username 'admin' and your password.
    displayName: PhotoPrism
    isOfficial: false
    description: AI-powered photo management app. Browse, organize, and share your photo collection with facial recognition and automatic tagging.
