captainVersion: 4
services:
    $$cap_appname:
        image: pihole/pihole:$$cap_pihole_version
        volumes:
            - $$cap_appname-etc:/etc/pihole
            - $$cap_appname-dnsmasq:/etc/dnsmasq.d
        restart: always
        environment:
            TZ: $$cap_timezone
            WEBPASSWORD: $$cap_password
        caproverExtra:
            containerHttpPort: 80
caproverOneClickApp:
    variables:
        - id: $$cap_pihole_version
          label: Pi-hole Version
          defaultValue: '2023.11.0'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/pihole/pihole/tags
          validRegex: /.{1,}/
        - id: $$cap_timezone
          label: Timezone
          defaultValue: America/New_York
        - id: $$cap_password
          label: Web Password
          description: Password for the admin interface
    instructions:
        start: Deploying Pi-hole network-wide ad blocker.
        end: Pi-hole has been deployed! Visit http://$$cap_appname.$$cap_root_domain/admin to access the dashboard.
    displayName: Pi-hole
    isOfficial: false
    description: Network-wide ad blocker. Block ads and tracking at the network level for all devices with DNS filtering.
