captainVersion: 4
services:
    $$cap_appname:
        image: prefecthq/prefect:$$cap_prefect_version
        volumes:
            - $$cap_appname-data:/root/.prefect
        restart: always
        command: prefect server start --host 0.0.0.0
        caproverExtra:
            containerHttpPort: 4200
caproverOneClickApp:
    variables:
        - id: $$cap_prefect_version
          label: Prefect Version
          defaultValue: '2.14.21'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/prefecthq/prefect/tags
          validRegex: /.{1,}/
    instructions:
        start: Deploying Prefect workflow orchestration.
        end: Prefect has been deployed! Visit http://$$cap_appname.$$cap_root_domain for the UI. Start building data workflows.
    displayName: Prefect
    isOfficial: false
    description: Modern workflow orchestration. Build, run, and monitor data pipelines with Python and intuitive API.
