captainVersion: 4
services:
    $$cap_appname:
        image: questdb/questdb:$$cap_questdb_version
        volumes:
            - $$cap_appname-data:/var/lib/questdb
        restart: always
        caproverExtra:
            containerHttpPort: 9000
caproverOneClickApp:
    variables:
        - id: $$cap_questdb_version
          label: QuestDB Version
          defaultValue: '7.3.10'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/questdb/questdb/tags
          validRegex: /.{1,}/
    instructions:
        start: Deploying QuestDB time-series database.
        end: QuestDB has been deployed! Visit http://$$cap_appname.$$cap_root_domain for the web console. Query on port 8812.
    displayName: QuestDB
    isOfficial: false
    description: High-performance time-series database. Fast SQL queries on time-series data with PostgreSQL wire protocol support.
