captainVersion: 4
services:
    $$cap_appname-db:
        image: mongo:$$cap_mongo_version
        volumes:
            - $$cap_appname-db-data:/data/db
        restart: always
        command: mongod --oplogSize 128 --replSet rs0
    $$cap_appname:
        image: rocketchat/rocket.chat:$$cap_rocketchat_version
        volumes:
            - $$cap_appname-uploads:/app/uploads
        restart: always
        environment:
            MONGO_URL: mongodb://$$cap_appname-db:27017/rocketchat?replicaSet=rs0
            MONGO_OPLOG_URL: mongodb://$$cap_appname-db:27017/local?replicaSet=rs0
            ROOT_URL: http://$$cap_appname.$$cap_root_domain
            PORT: '3000'
        depends_on:
            - $$cap_appname-db
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_rocketchat_version
          label: Rocket.Chat Version
          defaultValue: '6.5'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/rocketchat/rocket.chat/tags
          validRegex: /.{1,}/
        - id: $$cap_mongo_version
          label: MongoDB Version
          defaultValue: '6.0'
    instructions:
        start: Deploying Rocket.Chat team chat platform. Note - MongoDB replica set initialization may be required.
        end: Rocket.Chat has been deployed! Visit http://$$cap_appname.$$cap_root_domain to create your admin account.
    displayName: Rocket.Chat
    isOfficial: false
    description: Team chat platform with real-time messaging, video conferencing, and file sharing. Open-source alternative to Slack.
