captainVersion: 4
services:
    $$cap_appname-postgres:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: sentry
            POSTGRES_USER: sentry
            POSTGRES_PASSWORD: $$cap_db_password
    $$cap_appname-redis:
        image: redis:$$cap_redis_version
        restart: always
    $$cap_appname:
        image: sentry:$$cap_sentry_version
        restart: always
        environment:
            SENTRY_SECRET_KEY: $$cap_secret_key
            SENTRY_POSTGRES_HOST: $$cap_appname-postgres
            SENTRY_POSTGRES_PORT: '5432'
            SENTRY_DB_NAME: sentry
            SENTRY_DB_USER: sentry
            SENTRY_DB_PASSWORD: $$cap_db_password
            SENTRY_REDIS_HOST: $$cap_appname-redis
        depends_on:
            - $$cap_appname-postgres
            - $$cap_appname-redis
        caproverExtra:
            containerHttpPort: 9000
caproverOneClickApp:
    variables:
        - id: $$cap_sentry_version
          label: Sentry Version
          defaultValue: '24.1'
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/sentry/tags
          validRegex: /.{1,}/
        - id: $$cap_postgres_version
          label: PostgreSQL Version
          defaultValue: '15'
        - id: $$cap_redis_version
          label: Redis Version
          defaultValue: '7'
        - id: $$cap_db_password
          label: Database Password
        - id: $$cap_secret_key
          label: Secret Key
          description: Generate a random secret key (run 'sentry config generate-secret-key').
    instructions:
        start: Deploying Sentry error tracking platform.
        end: Sentry has been deployed! Visit http://$$cap_appname.$$cap_root_domain to create your account. You may need to run migrations first.
    displayName: Sentry
    isOfficial: false
    description: Error tracking and performance monitoring. Track errors, monitor performance, and improve code quality across your applications.
