captainVersion: 4
services:
    $$cap_appname:
        image: strapi/strapi:$$cap_strapi_version
        volumes:
            - $$cap_appname-data:/srv/app
        restart: always
        environment:
            DATABASE_CLIENT: sqlite
            DATABASE_FILENAME: .tmp/data.db
            NODE_ENV: production
        caproverExtra:
            containerHttpPort: 1337
caproverOneClickApp:
    variables:
        - id: $$cap_strapi_version
          label: Strapi Version
          defaultValue: '4.16'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/strapi/strapi/tags
          validRegex: /.{1,}/
    instructions:
        start: Deploying Strapi headless CMS.
        end: Strapi has been deployed! Visit http://$$cap_appname.$$cap_root_domain/admin to create your admin account.
    displayName: Strapi
    isOfficial: false
    description: Headless CMS with a customizable API. Build powerful APIs with no effort using a flexible content management system.
