captainVersion: 4
services:
    $$cap_appname:
        image: teamcity/teamcity-server:$$cap_teamcity_version
        volumes:
            - $$cap_appname-data:/data/teamcity_server/datadir
            - $$cap_appname-logs:/opt/teamcity/logs
        restart: always
        caproverExtra:
            containerHttpPort: 8111
caproverOneClickApp:
    variables:
        - id: $$cap_teamcity_version
          label: TeamCity Version
          defaultValue: '2023.11'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/jetbrains/teamcity-server/tags
          validRegex: /.{1,}/
    instructions:
        start: Deploying TeamCity CI/CD server by JetBrains.
        end: TeamCity has been deployed! Visit http://$$cap_appname.$$cap_root_domain to complete setup and create your first project.
    displayName: TeamCity
    isOfficial: false
    description: Powerful CI/CD server by JetBrains. Build, test, and deploy with advanced features and extensive integrations.
