captainVersion: 4
services:
    $$cap_appname-db:
        image: postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: zulip
            POSTGRES_USER: zulip
            POSTGRES_PASSWORD: $$cap_db_password
    $$cap_appname-redis:
        image: redis:$$cap_redis_version
        restart: always
    $$cap_appname:
        image: zulip/docker-zulip:$$cap_zulip_version
        volumes:
            - $$cap_appname-data:/data
        restart: always
        environment:
            DB_HOST: $$cap_appname-db
            DB_HOST_PORT: '5432'
            DB_USER: zulip
            SECRETS_postgres_password: $$cap_db_password
            SETTING_EXTERNAL_HOST: $$cap_appname.$$cap_root_domain
            SETTING_ZULIP_ADMINISTRATOR: $$cap_admin_email
            SECRETS_secret_key: $$cap_secret_key
            REDIS_HOST: $$cap_appname-redis
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-redis
        caproverExtra:
            containerHttpPort: 80
caproverOneClickApp:
    variables:
        - id: $$cap_zulip_version
          label: Zulip Version
          defaultValue: '8.3-0'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/zulip/docker-zulip/tags
          validRegex: /.{1,}/
        - id: $$cap_postgres_version
          label: PostgreSQL Version
          defaultValue: '15'
        - id: $$cap_redis_version
          label: Redis Version
          defaultValue: '7'
        - id: $$cap_db_password
          label: Database Password
        - id: $$cap_admin_email
          label: Admin Email
        - id: $$cap_secret_key
          label: Secret Key
          description: Generate a random secret key.
    instructions:
        start: Deploying Zulip team chat with threading.
        end: Zulip has been deployed! Visit http://$$cap_appname.$$cap_root_domain to access the platform.
    displayName: Zulip
    isOfficial: false
    description: Team chat with powerful threading. Organize conversations by topic for better collaboration and productivity.
